#!/usr/bin/env bash
mkdir test_data
cd test_data
wget https://cloudstor.aarnet.edu.au/plus/s/C0KkMvqtNWgOzEi
wget https://cloudstor.aarnet.edu.au/plus/s/tg5f9fk29uEjwiF
wget https://cloudstor.aarnet.edu.au/plus/s/D8ABZoKZmCjuxBG
wget https://cloudstor.aarnet.edu.au/plus/s/uFVFjlwK47VmGKI
wget https://cloudstor.aarnet.edu.au/plus/s/Ti9cvjWSKQPwiJm
wget https://cloudstor.aarnet.edu.au/plus/s/n5GBMzq0zU0jhNE
wget https://cloudstor.aarnet.edu.au/plus/s/AvaGSVPxhCfsRFl
wget https://cloudstor.aarnet.edu.au/plus/s/S4oNRTJS97rCIe1
wget https://cloudstor.aarnet.edu.au/plus/s/1Nv26lcfLBWWI4f
wget https://cloudstor.aarnet.edu.au/plus/s/qKyV1q8PgStXc1h
wget https://cloudstor.aarnet.edu.au/plus/s/3TxUIRPTCPwLk3L
wget https://cloudstor.aarnet.edu.au/plus/s/weIwMOvd5LuzMtS
wget https://cloudstor.aarnet.edu.au/plus/s/1GmS6zLVp9pXadQ
wget https://cloudstor.aarnet.edu.au/plus/s/MOsaXfIRpPXdLJI
wget https://cloudstor.aarnet.edu.au/plus/s/pECoBogbbpWqgo6
wget https://cloudstor.aarnet.edu.au/plus/s/VKRi9WPefaHUMQr
wget https://cloudstor.aarnet.edu.au/plus/s/4u163tdszkI7lpT
wget https://cloudstor.aarnet.edu.au/plus/s/dJ1SxOvQ0Ne3AzP
unzip test_data_*.zip
